// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Template.FRONTEND_TEMPLATE.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\asp dotnet project\AspDotnet_FrontEnd_Template\FRONTEND_TEMPLATE\Templates\ControllerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ControllerTemplate : ControllerTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 1 "D:\Projects\asp dotnet project\AspDotnet_FrontEnd_Template\FRONTEND_TEMPLATE\Templates\ControllerTemplate.tt"
  //To create runtime template change the custom tool proterty of the template from
// TextTemplatingFileGenerator to TextTemplatingFilePreprocessor
//If there is some error with sqldataclient use 
//"dotnet add package Microsoft.Data.SqlClient" to add the package

            
            #line default
            #line hidden
            this.Write("\r\n");
            this.Write(@"
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Template.Models;
using Template.Templates;
using System;
using System.Collections.Generic;


namespace Template.Controllers
{
    public class ");
            
            #line 26 "D:\Projects\asp dotnet project\AspDotnet_FrontEnd_Template\FRONTEND_TEMPLATE\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ControllerName));
            
            #line default
            #line hidden
            this.Write(@"Controller : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Get()
		{
			try
			{
				string TokenNo = HttpContext.Session.GetString(""TokenNo"");
				if (TokenNo == null)
				{
					return StatusCode(StatusCodes.Status504GatewayTimeout);
				}
				else
				{
					//string Response = await ApiCall.ApiCallWithObject(""");
            
            #line 47 "D:\Projects\asp dotnet project\AspDotnet_FrontEnd_Template\FRONTEND_TEMPLATE\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ControllerName));
            
            #line default
            #line hidden
            this.Write(@"/Get"", TokenNo, ""Get"");
					return StatusCode(StatusCodes.Status200OK, Response);
				}
			}
			catch (Exception ex)
			{
				string Exception = ex.ToString();
				return StatusCode(StatusCodes.Status417ExpectationFailed,Exception);
			}
		}

        [HttpGet]
        public async Task<IActionResult> GetByID(int id)
		{
			try
			{
				string TokenNo = HttpContext.Session.GetString(""TokenNo"");
				if (TokenNo == null)
				{
					return StatusCode(StatusCodes.Status504GatewayTimeout);
				}
				else
				{
					//string Response = await ApiCall.ApiCallWithObject(""");
            
            #line 70 "D:\Projects\asp dotnet project\AspDotnet_FrontEnd_Template\FRONTEND_TEMPLATE\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ControllerName));
            
            #line default
            #line hidden
            this.Write(@"/GetByID?id="" + id, TokenNo, ""Get"");
					return StatusCode(StatusCodes.Status200OK, Response);
				}
			}
			catch (Exception ex)
			{
				string Exception = ex.ToString();
				return StatusCode(StatusCodes.Status417ExpectationFailed,Exception);
			}
		}

		[HttpPut]
		public async Task<IActionResult> Update([FromBody]");
            
            #line 82 "D:\Projects\asp dotnet project\AspDotnet_FrontEnd_Template\FRONTEND_TEMPLATE\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ControllerName));
            
            #line default
            #line hidden
            this.Write(@"Model md)
		{
			try{
			   string TokenNo = HttpContext.Session.GetString(""TokenNo"");
			   if (TokenNo == null)
			   {
			       return StatusCode(StatusCodes.Status504GatewayTimeout);
				}
				else
				{
				    md.TokenNo = TokenNo;
					//string Response = await ApiCall.ApiCallWithObject(""");
            
            #line 93 "D:\Projects\asp dotnet project\AspDotnet_FrontEnd_Template\FRONTEND_TEMPLATE\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ControllerName));
            
            #line default
            #line hidden
            this.Write(@"/Update"", md, ""Put"");
					return StatusCode(StatusCodes.Status200OK, Response);
				}
			}
			catch (Exception ex)
			{
			    string Exception = ex.ToString();
				return StatusCode(StatusCodes.Status417ExpectationFailed,Exception);
			}
		}



        [HttpPost]
        public async Task<IActionResult> Create([FromBody]");
            
            #line 107 "D:\Projects\asp dotnet project\AspDotnet_FrontEnd_Template\FRONTEND_TEMPLATE\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ControllerName));
            
            #line default
            #line hidden
            this.Write(@"Model md )
        {
            try{
                string TokenNo = HttpContext.Session.GetString(""TokenNo"");
                if (TokenNo == null)
                {
                    return StatusCode(StatusCodes.Status504GatewayTimeout);
                }
                else
                {
                    md.TokenNo = TokenNo;
                    //string Response = await ApiCall.ApiCallWithObject(""");
            
            #line 118 "D:\Projects\asp dotnet project\AspDotnet_FrontEnd_Template\FRONTEND_TEMPLATE\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ControllerName));
            
            #line default
            #line hidden
            this.Write(@"/Create"", md, ""Post"");
                    return StatusCode(StatusCodes.Status200OK,Response);
                }
            }
             catch (Exception ex)
            {
                string Exception = ex.ToString();
                return StatusCode(StatusCodes.Status417ExpectationFailed,Exception);
            }
		}

        [HttpDelete]
		public async Task<IActionResult> Delete(int id)
		{
			try
			{
				string TokenNo = HttpContext.Session.GetString(""TokenNo"");
				if (TokenNo == null)
				{
					return StatusCode(StatusCodes.Status504GatewayTimeout);
				}
				else
				{
					//string Response = await ApiCall.ApiCallWithObject(""");
            
            #line 141 "D:\Projects\asp dotnet project\AspDotnet_FrontEnd_Template\FRONTEND_TEMPLATE\Templates\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ControllerName));
            
            #line default
            #line hidden
            this.Write(@"/Delete?id="" + id, TokenNo, ""Delete"");
					return StatusCode(StatusCodes.Status200OK, Response);
				}
			}
			catch (Exception ex)
			{
				string Exception = ex.ToString();
				return StatusCode(StatusCodes.Status417ExpectationFailed,Exception);
			}
		}
		
    }
}");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        /// <summary>
        /// The current host for the text templating engine
        /// </summary>
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class ControllerTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
